---
kind: pipeline
type: docker
name: lint

steps:
  - name: yaml linting
    image: pipelinecomponents/yamllint
    commands:
      - yamllint .
  - name: markdown linting
    image: 06kellyjac/markdownlint-cli
    commands:
      - markdownlint . --config .markdownlint.yaml

---
kind: pipeline
type: docker
name: test build

steps:
  - name: build
    image: squidfunk/mkdocs-material
    commands:
      - mkdocs build --clean --strict --verbose --site-dir build
trigger:
  event:
    exclude:
      - push
---
kind: pipeline
type: docker
name: deploy

steps:
  - name: build
    image: squidfunk/mkdocs-material
    commands:
      - mkdocs build --clean --strict --verbose --site-dir homelab

  - name: deploy
    image: appleboy/drone-scp
    when:
      status:
        - success
    settings:
      host: www.service.consul
      user: drone-deploy
      overwrite: true
      key:
        from_secret: dronePrivateKey
      target: /srv/http
      source: homelab

trigger:
  branch:
    - master
  event:
    - push

---
kind: secret
name: dronePrivateKey
get:
  path: secrets/droneci/keyRSA
  name: dronePrivateKey
