name: Homelab CI Workflow
on: push

env:
  PYTHON_VERSION: 3.x


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: https://github.com/karancode/yamllint-github-action@master
      - uses: https://github.com/DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
          config: .markdownlint.yaml

  build:
    runs-on: ubuntu-latest
    steps:     
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Python runtime
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements.txt
      - name: Set up build cache
        uses: actions/cache/restore@v4
        with:
          key: mkdocs-material-${{ hashfiles('.cache/**') }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
      - name: Build documentation
        run: |
            mkdocs build --clean --strict --verbose --site-dir homelab
      - name: copy on target
        if: github.ref == 'refs/heads/master'
        uses: https://github.com/appleboy/scp-action@v1
        with:
          host: www.service.consul
          username: drone-deploy
          key: ${{ secrets.PrivateKey }}
          target: /srv/http/
          source: homelab
  nomad_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nomad
        uses: https://github.com/hashicorp/setup-nomad@v1.0.0
      - name: Nomad plan
        run: |
          make -C nomad-job plan-all
        env:
          NOMAD_ADDR: http://nomad.service.consul:4646 
