name: Nomad Image Updater

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"
    
jobs:
  nid:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: download nid binaries
      run: wget https://git.ducamps.eu/vincent/nomad-image-updater/releases/download/1.0.0/nomad-image-updater && chmod +x ./nomad-image-updater
    - name: execute nid
      run: NID_GIT_REMOTETOKEN=${{ secrets.GITEAPAT }}  ./nomad-image-updater update .
            


