name: Nomad Image Updater

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"
    
jobs:
  nid:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: addnab/docker-run-action@v3
      with:
          image: ducampsv/nomad-image-updater:latest
          options:  --pull=always --volumes-from=${{ env.JOB_CONTAINER_NAME }} -e NID_GIT_REMOTETOKEN=${{ secrets.GITEAPAT }}
          run: |
            cd ${{ github.workspace }}
            /app/nomad-image-updater update .
            


