---
- hosts: all
  roles:
    - role: ansible-user
      vars:
        user_name: '{{ user.name }}'
        user_ldap: '{{ sssd_configure}}'
        user_password: '{{ userPassword }}'
        user_authorized_key: '{{ user.authorized_keys}}'
        user_privatekey: '{{ user.privatekey}}'
        user_shell: '/bin/zsh'
        user_uid: '{{ user.uid }}'
        user_groups:
          - docker
      become: true
      become_user: '{{ user.name }}'
