---
- hosts: all
  name: Hashicorp stack
  roles:
    - role: ansible-hashicorp-vault
      when: inventory_hostname not in groups['VPS']
      become: true
    - role: ansible-consul
      become: true
    - role: ansible-nomad
      become: true
    - role: docker
      become: true
