---
- name: gather all
  hosts: all
- name: NAS playbook
  hosts: NAS
  vars:
  # certbot_force: true
  pre_tasks:
    - name: include task NasBind
      ansible.builtin.include_tasks:
        file: tasks/NasBind.yml
      loop: "{{ nas_bind_source }}"
    - name: create nomad folder
      ansible.builtin.file:
        path: "{{ nas_bind_target }}/nomad/{{ item.name }}"
        owner: "{{ item.owner|default('root') }}"
        state: directory
      become: true
      loop: "{{ NAS_nomad_folder }}"
  roles:
    - role: ansible-role-nut
      become: true
    - role: ansible-role-nfs
      become: true
    - role: ansible-role-pureftpd
      become: true
    - role: vladgh.samba.server
      become: true
