---
prerun: false 
dependency:
  name: galaxy
  enabled: False
driver:
  name: lxd
platforms:
  - name: oscar-dev
    image: images:archlinux
    source:
      type: image
      mode: pull
      alias: archlinux
  - name: merlin-dev
    source:
      type: image
      mode: pull
      alias: rockylinux/9
  - name: gerard-dev
    source:
      type: image
      mode: pull
      alias: debian/11
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vincent
    ansible_become: true
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg
    ANSIBLE_ROLES_PATH: "../../roles"
  log: true
  lint:
    name: ansible-lint
  inventory:
    host_vars: []
    
    links:
      group_vars: ../../group_vars
      hosts: ../../staging
verifier:
  name: ansible
