---
- hosts: all
  remote_user: root
  roles:
    - ansible-arch-provissionning

- hosts: all
  remote_user: root
  vars:
    ansible_password: "{{ lookup('hashi_vault','secret=secrets/data/ansible/user:root') }}"
  roles:
    - ansible_bootstrap

- remote_user: "{{ user.name }}"
  import_playbook: site.yml
